###############################################################################
# Created by write_sdc
# Mon Sep  7 07:40:11 2026
###############################################################################
current_design housekeeping_spi
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name SCK -period 10.0000 [get_ports {SCK}]
set_clock_transition 0.1500 [get_clocks {SCK}]
set_clock_uncertainty 0.2500 SCK
set_propagated_clock [get_clocks {SCK}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {CSB}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {SDI}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {idata[0]}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {idata[1]}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {idata[2]}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {idata[3]}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {idata[4]}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {idata[5]}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {idata[6]}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {idata[7]}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {reset}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {SDO}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {oaddr[0]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {oaddr[1]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {oaddr[2]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {oaddr[3]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {oaddr[4]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {oaddr[5]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {oaddr[6]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {oaddr[7]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {odata[0]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {odata[1]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {odata[2]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {odata[3]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {odata[4]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {odata[5]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {odata[6]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {odata[7]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {pass_thru_mgmt}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {pass_thru_mgmt_delay}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {pass_thru_mgmt_reset}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {pass_thru_user}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {pass_thru_user_delay}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {pass_thru_user_reset}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {rdstb}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {sdoenb}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {wrstb}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {SDO}]
set_load -pin_load 0.0334 [get_ports {pass_thru_mgmt}]
set_load -pin_load 0.0334 [get_ports {pass_thru_mgmt_delay}]
set_load -pin_load 0.0334 [get_ports {pass_thru_mgmt_reset}]
set_load -pin_load 0.0334 [get_ports {pass_thru_user}]
set_load -pin_load 0.0334 [get_ports {pass_thru_user_delay}]
set_load -pin_load 0.0334 [get_ports {pass_thru_user_reset}]
set_load -pin_load 0.0334 [get_ports {rdstb}]
set_load -pin_load 0.0334 [get_ports {sdoenb}]
set_load -pin_load 0.0334 [get_ports {wrstb}]
set_load -pin_load 0.0334 [get_ports {oaddr[7]}]
set_load -pin_load 0.0334 [get_ports {oaddr[6]}]
set_load -pin_load 0.0334 [get_ports {oaddr[5]}]
set_load -pin_load 0.0334 [get_ports {oaddr[4]}]
set_load -pin_load 0.0334 [get_ports {oaddr[3]}]
set_load -pin_load 0.0334 [get_ports {oaddr[2]}]
set_load -pin_load 0.0334 [get_ports {oaddr[1]}]
set_load -pin_load 0.0334 [get_ports {oaddr[0]}]
set_load -pin_load 0.0334 [get_ports {odata[7]}]
set_load -pin_load 0.0334 [get_ports {odata[6]}]
set_load -pin_load 0.0334 [get_ports {odata[5]}]
set_load -pin_load 0.0334 [get_ports {odata[4]}]
set_load -pin_load 0.0334 [get_ports {odata[3]}]
set_load -pin_load 0.0334 [get_ports {odata[2]}]
set_load -pin_load 0.0334 [get_ports {odata[1]}]
set_load -pin_load 0.0334 [get_ports {odata[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {CSB}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCK}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SDI}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {reset}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {idata[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {idata[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {idata[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {idata[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {idata[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {idata[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {idata[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {idata[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_fanout 10.0000 [current_design]
